import { spawnSync } from "node:child_process";
import { cp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const distDirectory = path.join(projectRoot, "dist");
const docsDirectory = path.join(projectRoot, "docs");
const markerPath = path.join(docsDirectory, ".manual-vite-output");

function run(command, args, options = {}) {
  const result = spawnSync(command, args, {
    cwd: projectRoot,
    encoding: "utf8",
    stdio: options.capture ? "pipe" : "inherit",
    env: options.env ?? process.env,
    shell: process.platform === "win32" && command === "npm",
  });

  if (result.error) throw result.error;
  if (result.status !== 0) process.exit(result.status ?? 1);
  return result.stdout?.trim() ?? "";
}

const branch = run("git", ["branch", "--show-current"], { capture: true });
if (branch !== "main") {
  throw new Error(`Manual publishing must run on main; current branch is "${branch}".`);
}

const workingTree = run("git", ["status", "--porcelain"], { capture: true });
if (workingTree) {
  throw new Error("Commit and push source changes first. This command requires a clean working tree.");
}

if (existsSync(docsDirectory) && !existsSync(markerPath)) {
  throw new Error("Refusing to overwrite docs/: it is not marked as generated deployment output.");
}

const environment = { ...process.env, VITE_BASE_PATH: "/My-World/" };
run("npm", ["run", "build"], { env: environment });

const builtHtml = await readFile(path.join(distDirectory, "index.html"), "utf8");
if (builtHtml.includes("/src/main.tsx") || builtHtml.includes("%BASE_URL%")) {
  throw new Error("Vite output still contains source-only asset references; refusing to publish.");
}

if (existsSync(docsDirectory)) {
  await rm(docsDirectory, { recursive: true, force: true });
}
await mkdir(docsDirectory, { recursive: true });
await cp(distDirectory, docsDirectory, { recursive: true });
await writeFile(path.join(docsDirectory, ".nojekyll"), "");
await writeFile(markerPath, "Generated by npm run deploy:manual.\n");

run("git", ["add", "--all", "--", "docs"]);
const stagedFiles = run("git", ["diff", "--cached", "--name-only"], { capture: true });
if (!stagedFiles) {
  console.log("Generated site is unchanged; nothing to commit or push.");
  process.exit(0);
}

run("git", ["commit", "-m", "Deploy site to GitHub Pages"]);
run("git", ["push", "origin", "main"]);